### ISSUE TITLE
Have assert_ids print messages appear in error logs

### ISSUE THREAD

**Issue by davidshaw2018** [cran/assertable#1]
Hey Grant, minor fix I'd like to request - when assert_ids/assert_values/etc. fail, the offending rows are printed as output rather than included in the error message. I think it'd be easier to parse if included in the error message instead.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
